[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.0.3"
edition = "2024"
license = "MPL-2.0"
authors = ["Yamrc <yamrci@outlook.com>"]

[workspace.dependencies]
tracing = "0.1.44"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
